### ISSUE TITLE
Birthday Issue

### ISSUE THREAD

**Issue by 2021Josh** [DrMikeyS/COVIDVaccinePatientSlips#49]
When generating patient stickers birthdays that are 31st of the month are changed to the 1st of the same month. The CSV document used to generate the stickers is correct however.

**Comment by DrMikeyS** [comment]
Could you try the latest dev release:
https://github.com/DrMikeyS/COVIDVaccinePatientSlips/archive/refs/heads/v3dev.zip

It should all be solved in this.

**Comment by 2021Josh** [comment]
Hi

I tried using the new release you link to me; the issue is still occurring. Anything else I can try or is it an error.

Thanks Josh

________________________________

**Comment by 2021Josh** [comment]
Hope this works.

Thanks Josh
________________________________

**Comment by DrMikeyS** [comment]
Thanks Josh. It does indeed look to be a coding issue. Odd that has never come up for us. Either way, worth fixing so thanks for pointing out.
Try the update latest release and let me know how you get on:
https://github.com/DrMikeyS/COVIDVaccinePatientSlips/archive/refs/heads/v3dev.zip

**Comment by 2021Josh** [comment]
That seems to be all correct now!

Thank you Josh
________________________________
